import { StyleSheet } from "react-native";

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: "#F7F2F2",
  },
  page: {
    height: "90%",
    width: "90%",
    backgroundColor: "#FAFAFA",
    alignSelf: "center",
    top: 44,
  },
  titleBar: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: "Nunito_900Black",
    fontSize: 32,
    padding: 20,
    alignSelf: "center",
  },
  separator: {
    borderBottomColor: "#B89A59",
    borderBottomWidth: StyleSheet.hairlineWidth * 5,
  },
  container: {
    height: "80%",
    width: "90%",
    alignSelf: "center",
    marginVertical: 20,
    borderColor: "#AAAAAA",
    borderWidth: 1,
  },
  header: {
    flex: 1,
    flexDirection: "row",
    paddingVertical: 8,
    justifyContent: "space-evenly",
  },
  headerText: {
    fontFamily: "Nunito_400Regular",
    fontSize: 24,
    textAlign: "center",
    alignSelf: "center",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#AAAAAA",
    backgroundColor: "#DDDDDD",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  cell: {
    fontFamily: "Nunito_400Regular",
    fontSize: 24,
    textAlign: "center",
    alignSelf: "center",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#AAAAAA",
  },
  actions: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#AAAAAA",
    justifyContent: "center",
  },
  icons: {
    alignItems: "center",
    width: "50%",
  },
  bar: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "100%",
    padding: 10,
  },
  dropdown: {
    width: 200,
    height: 30,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 4,
    backgroundColor: "#EEEEEE",
  },
  searchbar: {
    width: 500,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: "#EEEEEE",
    height: 30,
  },
  button: {
    width: 260,
    height: 40,
    backgroundColor: "#B89A59",
    borderRadius: 20,
  },
  btnText: {
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    textAlign: "center",
    padding: 10,
    color: "#fff",
  },
  switchButtons: {
    flexDirection: "row",
    position: "absolute",
    right: 200,
    justifyContent: "center",
    backgroundColor: "#eee",
    borderRadius: 20,
    padding: 5,
    height: 40,
  },
  activeTab: {
    backgroundColor: "#B89A59",
    paddingVertical: 6,
    paddingHorizontal: 30,
    borderRadius: 20,
  },
  inactiveTab: {
    backgroundColor: "#eee",
    paddingVertical: 6,
    paddingHorizontal: 30,
    borderRadius: 20,
  },
  activeText: {
    color: "#fff",
    fontSize: 14,
    textAlign: "center",
  },
  inactiveText: {
    color: "#888",
    fontSize: 14,
    textAlign: "center",
  },
});
