import { StyleSheet } from "react-native";

export default StyleSheet.create({
	background: {
		flex: 1,
		backgroundColor: "#F7F2F2",
	},
	page: {
		height: "90%",
		width: "90%",
		backgroundColor: "#FAFAFA",
		alignSelf: "center",
		top: 44,
	},
	titleBar: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	title: {
		fontFamily: "Nunito_900Black",
		fontSize: 32,
		padding: 20,
		alignSelf: "center",
	},
	subtitle: {
		fontFamily: "Nunito_900Black",
		fontSize: 22,
	},
	separator: {
		borderBottomColor: "#B89A59",
		borderBottomWidth: StyleSheet.hairlineWidth * 5,
	},
	container: {
		height: "80%",
		width: "95%",
		alignSelf: "center",
		marginVertical: 20,
		borderColor: "#AAAAAA",
		borderWidth: 1,
	},
	header: {
		flex: 1,
		flexDirection: "row",
		paddingVertical: 8,
		justifyContent: "space-evenly",
	},
	headerText: {
		fontFamily: "Nunito_400Regular",
		fontSize: 24,
		textAlign: "center",
		alignSelf: "center",
		borderTopWidth: 1,
		borderBottomWidth: 1,
		borderColor: "#AAAAAA",
		backgroundColor: "#DDDDDD",
	},
	row: {
		flexDirection: "row",
		justifyContent: "space-evenly",
		borderBottomWidth: 1,
		borderColor: "#AAAAAA",
		alignItems: "center",
		minHeight: 50,
	},
	cell: {
		fontFamily: "Nunito_400Regular",
		fontSize: 24,
		textAlign: "center",
		alignSelf: "center",
		borderColor: "#AAAAAA",
	},
	actions: {
		flexDirection: "row",

		borderColor: "#AAAAAA",
		justifyContent: "center",
	},
	icons: {
		alignItems: "center",
		width: "50%",
	},
	bar: {
		flexDirection: "row",
		justifyContent: "space-evenly",
		width: "100%",
		padding: 10,
		alignItems: "center",
	},
	dropdown: {
		width: 200,
		height: 30,
		borderWidth: 1,
		borderRadius: 5,
		paddingHorizontal: 4,
		backgroundColor: "#EEEEEE",
	},
	searchbar: {
		width: 500,
		height: 30,
		borderRadius: 5,
		borderWidth: 1,
		backgroundColor: "#EEEEEE",
		color: "#000000",
		paddingHorizontal: 4,
		margin: 0,
	},
	inputContainer: {
		backgroundColor: "transparent",
	},
	searchbarContainer: {
		backgroundColor: "transparent",
		borderTopWidth: 0,
		borderBottomWidth: 0,
		padding: 0,
	},
	button: {
		width: 260,
		height: 40,
		backgroundColor: "#B89A59",
		borderRadius: 20,
	},
	btnText: {
		fontFamily: "Nunito_400Regular",
		fontSize: 16,
		textAlign: "center",
		padding: 10,
		color: "#fff",
	},
	switchButtons: {
		flexDirection: "row",
		position: "absolute",
		right: 20,
		justifyContent: "center",
		backgroundColor: "#eee",
		borderRadius: 20,
		padding: 5,
		height: 40,
	},
	activeTab: {
		backgroundColor: "#B89A59",
		paddingVertical: 6,
		paddingHorizontal: 30,
		borderRadius: 20,
	},
	inactiveTab: {
		backgroundColor: "#eee",
		paddingVertical: 6,
		paddingHorizontal: 30,
		borderRadius: 20,
	},
	activeText: {
		color: "#fff",
		fontSize: 14,
		textAlign: "center",
	},
	inactiveText: {
		color: "#888",
		fontSize: 14,
		textAlign: "center",
	},
	overlayWindow: {
		width: 850,
		height: 600,
	},
	saveButton: {
		flexDirection: "row",
		justifyContent: "flex-end",
		width: "100%",
		paddingRight: 40,
	},
	columns: {
		height: "80%",
		width: "85%",
		flexWrap: "wrap",
		flexDirection: "column",
		justifyContent: "space-evenly",
		margin: 50,
	},
	rows: {
		width: "50%",
		flexDirection: "row",
		justifyContent: "space-evenly",
	},
	input: {
		width: 200,
		height: 30,
		borderRadius: 5,
		borderWidth: 1,
		padding: 4,
		backgroundColor: "#EEEEEE",
	},
	square: {
		width: 300,
		height: 200,
		borderWidth: 1,
		alignItems: "center",
		justifyContent: "center",
		marginVertical: 10,
	},
	seleccionar: {
		width: 120,
		height: 25,
		borderWidth: 1,
		borderRadius: 10,
		textAlign: "center",
		marginVertical: 10,
	},
	cellText: {
		fontFamily: "Nunito_400Regular",
		fontSize: 20,
		textAlign: "left",
		paddingHorizontal: 6,
		color: "#000",
	},

	nameCell: {
		flexDirection: "row",
		alignItems: "center",
	},

	iconImage: {
		width: 34,
		height: 34,
		marginRight: 6,
		borderRadius: 4,
	},

	headerText: {
		fontFamily: "Nunito_700Bold",
		fontSize: 16,
		textAlign: "left",
		alignSelf: "center",
		borderTopWidth: 1,
		borderBottomWidth: 1,
		borderColor: "#AAAAAA",
		backgroundColor: "#DDDDDD",
		paddingHorizontal: 6,
	},
});
