import { StyleSheet } from "react-native";

export default StyleSheet.create({
	background: {
		flex: 1,
		backgroundColor: "#F5F5F5",
	},
	page: {
		height: "90%",
		width: "90%",
		backgroundColor: "#FFFFFF",
		alignSelf: "center",
		marginTop: 40,
		borderRadius: 12,
		padding: 20,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 6,
		elevation: 4,
	},
	title: {
		fontFamily: "Nunito_900Black",
		fontSize: 28,
		textAlign: "center",
		marginBottom: 10,
		color: "#1E1E1E",
	},
	separator: {
		borderBottomColor: "#B89A59",
		borderBottomWidth: 3,
		width: "100%",
		marginBottom: 20,
	},
	container: {
		flex: 1,
		width: "100%",
		alignSelf: "center",
	},
	containerRows: {
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "space-between",
		alignItems: "flex-start",
		marginBottom: 20,
	},
	containerCols: {
		flexDirection: "column",
		justifyContent: "space-evenly",
		marginHorizontal: 10,
		marginBottom: 10,
	},
	menuRows: {
		flexDirection: "row",
		alignItems: "center",
		marginVertical: 5,
	},
	label: {
		fontFamily: "Nunito_400Regular",
		fontSize: 16,
		marginRight: 8,
		color: "#333",
	},
	dropdown: {
		width: 200,
		height: 38,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#D0D0D0",
		paddingHorizontal: 10,
		backgroundColor: "#FAFAFA",
		fontFamily: "Nunito_400Regular",
		fontSize: 15,
	},
	filter: {
		width: 150,
		height: 38,
		borderRadius: 20,
		backgroundColor: "#B89A59",
		fontFamily: "Nunito_400Regular",
		fontSize: 16,
		color: "#fff",
		textAlign: "center",
		textAlignVertical: "center",
		lineHeight: 38,
		alignSelf: "flex-end",
	},
	text: {
		fontFamily: "Nunito_400Regular",
		fontSize: 18,
		textAlign: "center",
		color: "#777",
		marginTop: 20,
	},
	error: {
		fontFamily: "Nunito_700Bold",
		fontSize: 16,
		color: "#D9534F",
		textAlign: "center",
		marginTop: 15,
	},
});
