import { StyleSheet } from "react-native";

export default StyleSheet.create({
  table: {
    width: "100%",
  },
  header: {
    flex: 12,
    flexDirection: "row",
    paddingVertical: 6,
    backgroundColor: "#F3F3F3",
    borderBottomWidth: 1,
    borderColor: "#CCCCCC",
  },
  headerText: {
    flex: 1,
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    textAlign: "left",
    paddingHorizontal: 6,
    color: "#333333",
  },
  row: {
    flexDirection: "row",
    justifyContent: "flex-start",
    borderBottomWidth: 1,
    borderColor: "#E0E0E0",
    backgroundColor: "#FFFFFF",
    paddingVertical: 4,
  },
  cell: {
    flex: 1,
    fontFamily: "Nunito_400Regular",
    fontSize: 13,
    textAlign: "left",
    paddingHorizontal: 6,
    color: "#444444",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: "#FAFAFA",
    borderTopWidth: 1,
    borderColor: "#CCCCCC",
    paddingVertical: 6,
  },
  title: {
    fontFamily: "Nunito_900Black",
    fontSize: 20,
    width: "100%",
    textAlign: "left",
    color: "#222222",
    marginVertical: 10,
    paddingHorizontal: 6,
  },
  text: {
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    alignSelf: "left",
    marginVertical: 20,
    color: "#555555",
  },
  dataText: {
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    alignSelf: "left",
    marginVertical: 20,
    color: "#333333",
  },
  noDataText: {
    marginTop: 60,
    marginHorizontal: 20,
    backgroundColor: "#F8F8F8",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 3.5,
    elevation: 3,
    borderRadius: 8,
    textAlign: "center",
    color: "#E63946",
    fontWeight: "bold",
    fontSize: 16,
  },
});